language: php

sudo: false

notifications:
  on_success: never
  on_failure: change

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_install:
  - pip install --user codecov
  - composer install --dev

before_script:
  - travis_retry composer install --dev --no-interaction

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
  - ./vendor/bin/php-coveralls
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clove

after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)
